name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod download

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52

      - name: Build
        run: go build -v ./...
